import type { PlayerStats } from "./api";

export const POSITION_PRESETS: Record<string, PlayerStats> = {
  ST:  { age: 24, overall: 78, potential: 82, international_reputation: 2, pace: 82, shooting: 83, passing: 70, dribbling: 78, defending: 35, physic: 75, movement_acceleration: 83, movement_sprint_speed: 81, power_stamina: 74, power_strength: 76, mentality_vision: 68, mentality_composure: 76, skill_ball_control: 77, attacking_finishing: 82, mentality_positioning: 83, mentality_aggression: 72 },
  CAM: { age: 23, overall: 76, potential: 83, international_reputation: 2, pace: 76, shooting: 73, passing: 82, dribbling: 83, defending: 38, physic: 65, movement_acceleration: 77, movement_sprint_speed: 75, power_stamina: 72, power_strength: 62, mentality_vision: 83, mentality_composure: 79, skill_ball_control: 83, attacking_finishing: 73, mentality_positioning: 78, mentality_aggression: 55 },
  CM:  { age: 25, overall: 77, potential: 80, international_reputation: 2, pace: 70, shooting: 68, passing: 80, dribbling: 76, defending: 62, physic: 74, movement_acceleration: 71, movement_sprint_speed: 69, power_stamina: 82, power_strength: 70, mentality_vision: 79, mentality_composure: 77, skill_ball_control: 78, attacking_finishing: 66, mentality_positioning: 70, mentality_aggression: 68 },
  CDM: { age: 26, overall: 76, potential: 79, international_reputation: 1, pace: 66, shooting: 58, passing: 74, dribbling: 68, defending: 80, physic: 80, movement_acceleration: 67, movement_sprint_speed: 65, power_stamina: 83, power_strength: 80, mentality_vision: 72, mentality_composure: 75, skill_ball_control: 70, attacking_finishing: 54, mentality_positioning: 68, mentality_aggression: 80 },
  CB:  { age: 27, overall: 78, potential: 80, international_reputation: 1, pace: 68, shooting: 48, passing: 65, dribbling: 55, defending: 84, physic: 83, movement_acceleration: 68, movement_sprint_speed: 67, power_stamina: 77, power_strength: 84, mentality_vision: 64, mentality_composure: 78, skill_ball_control: 58, attacking_finishing: 42, mentality_positioning: 62, mentality_aggression: 80 },
  LB:  { age: 25, overall: 75, potential: 79, international_reputation: 1, pace: 80, shooting: 55, passing: 72, dribbling: 72, defending: 76, physic: 74, movement_acceleration: 81, movement_sprint_speed: 79, power_stamina: 80, power_strength: 72, mentality_vision: 68, mentality_composure: 72, skill_ball_control: 71, attacking_finishing: 50, mentality_positioning: 66, mentality_aggression: 72 },
  LW:  { age: 22, overall: 76, potential: 84, international_reputation: 2, pace: 86, shooting: 74, passing: 74, dribbling: 85, defending: 32, physic: 63, movement_acceleration: 87, movement_sprint_speed: 85, power_stamina: 76, power_strength: 60, mentality_vision: 74, mentality_composure: 72, skill_ball_control: 84, attacking_finishing: 74, mentality_positioning: 72, mentality_aggression: 52 },
  GK:  { age: 28, overall: 80, potential: 82, international_reputation: 2, pace: 52, shooting: 20, passing: 52, dribbling: 30, defending: 15, physic: 72, movement_acceleration: 52, movement_sprint_speed: 50, power_stamina: 68, power_strength: 70, mentality_vision: 70, mentality_composure: 80, skill_ball_control: 30, attacking_finishing: 15, mentality_positioning: 25, mentality_aggression: 50 },
};